M48
; DRILL file {KiCad 8.0.0} date 2024-04-15T20:03:39+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-04-15T20:03:39+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0236
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X5.2159Y-1.2579
X5.4435Y-1.2579
T2
X5.61Y-3.61
X5.8Y-1.18
M30
